name = "my-brand-redirect-worker"
main = "worker.js" # <<< Change this line from "src/index.js"
compatibility_date = "2024-06-23" # Keep your chosen date or update to a recent one

# Environment variables for different deployments
[vars]
AU_PREFIX = "AU213" # This will be overridden per account/deployment