name = "au-redirects"
main = "worker.js"
compatibility_date = "2024-06-23"

[observability.logs]
enabled = true

# These will be replaced dynamically in your GitHub Action
account_id = "REPLACED_ACCOUNT_ID"
workers_dev = true

# Corrected Observability Logs configuration
[observability.logs] # <--- Use this explicit sub-table header
enabled = true       # <--- Define 'enabled' directly under this sub-table

[vars]
AU_PREFIX = "REPLACED_AU_PREFIX"
DYN2 = "REPLACED_DYN2"           
DYN3 = "REPLACED_DYN3" 

[[kv_namespaces]]
binding = "BRAND_LINKS"
id = "REPLACED_KV_ID"


# NEW: D1 Database binding
[[d1_databases]]
binding = "DB" # This is the variable name your Worker code will use (e.g., env.DB)
database_name = "click_tracking_db" # The name you gave your D1 database in Cloudflare
database_id = "REPLACED_D1_DB_ID" # NEW: Placeholder for dynamic D1 Database ID