name = "my-brand-redirect-worker"
main = "worker.js"
compatibility_date = "2024-06-23"

[observability.logs]
enabled = true

# These will be replaced dynamically in your GitHub Action
account_id = "REPLACED_ACCOUNT_ID"
workers_dev = true

[vars]
AU_PREFIX = "REPLACED_AU_PREFIX"
DYN2 = "REPLACED_DYN2"           
DYN3 = "REPLACED_DYN3" 

[[kv_namespaces]]
binding = "BRAND_LINKS"
id = "REPLACED_KV_ID"