name: Deploy Cloudflare Workers and KV Data

on:
  push:
    branches:
      - main
    paths:
      - 'worker.js'
      - 'wrangler.toml'
      - 'brands_data.json'

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - account: "AU218"
            dyn2: "99"
            dyn3: "77"
          # Add more accounts and their specific dyn2/dyn3 here

    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets[format('CLOUDFLARE_API_TOKEN_{0}', matrix.account)] }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets[format('CLOUDFLARE_ACCOUNT_ID_{0}', matrix.account)] }}
      KV_NAMESPACE_ID: ${{ secrets[format('KV_NAMESPACE_ID_{0}', matrix.account)] }}
      DYN2: ${{ matrix.dyn2 }}
      DYN3: ${{ matrix.dyn3 }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Wrangler CLI
        run: npm install -g wrangler

      - name: Install jq (for JSON parsing)
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Perform Deployment for ${{ matrix.account }}
        run: |
          set -e

          export AU_PREFIX=${{ matrix.account }}

          echo "--- Deploying to Cloudflare account: $AU_PREFIX ---"
          echo "  Account ID: $CLOUDFLARE_ACCOUNT_ID"
          echo "  KV Namespace ID: $KV_NAMESPACE_ID"
          echo "  dyn2 = $DYN2"
          echo "  dyn3 = $DYN3"

          echo "⏫ Uploading KV pairs..."

          jq -c '.[]' brands_data.json | while read -r line; do
            ID=$(echo "$line" | jq -r '.id')

            VALUE=$(echo "$line" | jq -c \
              --arg prefix "$AU_PREFIX" \
              --arg dyn2 "$DYN2" \
              --arg dyn3 "$DYN3" '
              {
                baseUrl: .baseUrl,
                fullQueryStringTemplate: (
                  .fullQueryStringTemplate
                  | gsub("\\{ACCOUNT_PREFIX\\}"; $prefix)
                  | gsub("\\{DYN2\\}"; $dyn2)
                  | gsub("\\{DYN3\\}"; $dyn3)
                )
              }
            ')

            echo "  ↳ Uploading KV key: $ID"
            wrangler kv:key put "$ID" "$VALUE" --namespace-id "$KV_NAMESPACE_ID" --remote
          done

          echo "✅ KV data upload complete for $AU_PREFIX."

          # --- Deploy Worker ---
          NAME="$(echo "${{ matrix.account }}" | tr '[:upper:]' '[:lower:]')-brand-redirect"

          echo "🚀 Deploying Worker: $NAME"

          wrangler deploy --minify \
            --name "$NAME" \
            --compatibility-date "2024-06-23" \
            --var AU_PREFIX="$AU_PREFIX"

          echo "--- Worker deployed for $AU_PREFIX ---"
          echo "--------------------------------------"
